version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
      dockerfile: Dockerfile

  client:
    image: client 
    build: 
      context: ../client
      dockerfile: Dockerfile
   
#  proxy:
#   image: nginx:mainline
#    ports:
#      - "443:80"
